version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: no
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: linktree_node_typescript
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
# Cadena de conexión:
# mongodb://root:example@localhost:27017/
